title: "Ruiao Jiao"
author: "Ruiao Jiao"
description: "Ruiao Jiao's Personal Website"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home"}
  - {file: "README.md", title: "About"}
  - {file: "PersonalInfo.md", title: "Resume"}
  - {file: "post.md", title: "Post"}

paginate_path: "posts/page: num/"

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope-open, url: "mailto:jiaoruiao@gmail.com"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/ruiao-jiao"}
  - {title: Github, icon: github, url: "https://github.com/ruiaojiao"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
